site_name: IKIM Cluster
site_url: https://k87rte.github.io/portfolio
copyright: Copyright &copy; 2023 Institut für künstliche Intelligenz in der Medizin (IKIM), Essen

theme:
  name: material
  features:
    - navigation.sections

markdown_extensions:
  - footnotes
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

nav:

  - User Guide:
     - aboutme: aboutme.md
